server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Test
    username: 
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

